# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    # take from https://github.com/gotk3/gotk3/blob/master/.github/workflows/linux.yml
    - name: Install gtk Dependencies
      run: |
        sudo apt update
        sudo apt install libgtk-3-dev libcairo2-dev libglib2.0-dev libgtk2.0-dev
    
    - name: Print versions
      run: |
        echo glib: $(pkg-config --modversion glib-2.0)
        echo gdk: $(pkg-config --modversion gdk-3.0)
        echo gtk: $(pkg-config --modversion gtk+-3.0)
    
    - name: Build
      run: go build --tags=glib_deprecated -v ./...
